# Generated by Django 4.2 on 2025-07-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='article_files/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
