# Generated by Django 4.2 on 2025-07-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_uploaded_file_alter_article_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='audio',
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(),
        ),
    ]
