# Generated by Django 4.2 on 2025-07-26 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestreamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название комнаты')),
                ('type', models.CharField(choices=[('broadcast', 'Прямой эфир'), ('conference', 'Конференция')], default='broadcast', max_length=20, verbose_name='Тип')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ведущий')),
            ],
            options={
                'verbose_name': 'Комната трансляции',
                'verbose_name_plural': 'Комнаты трансляций',
                'ordering': ['-started_at'],
            },
        ),
    ]
