# Generated by Django 4.2 on 2025-07-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_alter_livestreamroom_options_livestreamroom_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreamroom',
            name='channel_id',
            field=models.CharField(default='ardar-migration', max_length=64, unique=True, verbose_name='Channel ID (латиница/цифры)'),
            preserve_default=False,
        ),
    ]
