# Generated by Django 4.2 on 2025-07-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0003_livestreamroom_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreamparticipant',
            name='is_kicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livestreamparticipant',
            name='waiting_approval',
            field=models.BooleanField(default=False),
        ),
    ]
