# Generated by Django 4.2 on 2025-07-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0004_livestreamparticipant_is_kicked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreamparticipant',
            name='can_enable_camera',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livestreamparticipant',
            name='can_enable_mic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livestreamparticipant',
            name='hand_raised',
            field=models.BooleanField(default=False),
        ),
    ]
