# Generated by Django 4.2 on 2025-08-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0005_livestreamparticipant_can_enable_camera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestreamroom',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='livestreamroom',
            name='type',
        ),
    ]
